- hosts: localhost
  vars_prompt:
  - name: container_name
    prompt: "Enter Docker Container Name :"
    private: no
  - name: inventory_path
    prompt: "Enter Ansible Inventory Path: "
    private: no

  tasks:
  - name: Configuring yum repo for Docker
    yum_repository:
          name: docker
          file: docker
          description: docker repo
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
          gpgcheck: no

  - name: Install Docker-ce
    package:
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present

  - name: Start and Enable Docker Services
    service:
          name: "docker"
          state: started
          enabled: yes

  - name: Installing Docker SDK for python3
    pip:
          name: docker

  - name: Pull Docker Image
    docker_image:
          name: "sshcentos:latest"
          source: pull

  - name: "Launching {{ container_name }} container"
    docker_container:
          name: "{{ container_name }}"
          image: "sshcentos:latest"
          state: started
          interactive: yes
          detach: yes
          tty: yes

  - name: "Docker Container Info"
    docker_container_info:
         name: "{{ container_name }}"
    register: docker_info

  - debug:
         var: docker_info.container.NetworkSettings.IPAddress

  - name: "Retrieving IP dynamically and updating in the Inventory file"
    template:
            src: "dockerip.txt"
            dest: "{{ inventory_path }}"
